/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#0f131c',
        'surface-dim': '#0f131c',
        'surface-bright': '#353942',
        'surface-container-lowest': '#0a0e16',
        'surface-container-low': '#181c24',
        'surface-container': '#1c2028',
        'surface-container-high': '#262a33',
        'surface-container-highest': '#31353e',
        'on-surface': '#dfe2ee',
        'on-surface-variant': '#bbcabf',
        outline: '#86948a',
        'outline-variant': '#3c4a42',
        primary: '#4edea3',
        'on-primary': '#003824',
        'primary-container': '#10b981',
        'on-primary-container': '#00422b',
        secondary: '#7bd0ff',
        'on-secondary': '#00354a',
        'secondary-container': '#00a6e0',
        tertiary: '#c0c1ff',
        'on-tertiary': '#1000a9',
        'tertiary-container': '#9699ff',
        'primary-fixed': '#6ffbbe',
        background: '#0f131c',
        'on-background': '#dfe2ee',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Hanken Grotesk"', 'sans-serif'],
        mono: ['"Space Grotesk"', 'monospace'],
      },
      fontSize: {
        'display-hero': ['64px', { lineHeight: '72px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-hero-mobile': ['38px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-code': ['13px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '700' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'space-2xl': '4rem',
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '3rem',
        'margin-mobile': '1.25rem',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
      },
    },
  },
  plugins: [],
}
